---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    # velocity.tech.v1/id: {{ .Values.analyticsService.annotations.velocityID | quote }}
    # velocity.tech.v1/dependsOn: {{ .Values.analyticsService.annotations.velocityDependsOn | quote }}
  name: analytics-ser
  labels:
    app: analytics-ser
spec:
  selector:
    matchLabels:
      api: analytics-ser
  replicas: 1
  template:
    metadata:
      labels:
        app: analytics-ser
        api: analytics-ser
    spec:
      containers:
        - name: analytics-ser
          image: jdvincent/gin-redis-analytics-service:latest
          env:
            - name: MONGO2_HOST
              value: {{ .Values.analyticsService.envVars.MONGO2_HOST | quote  }}
            - name: MONGO2_PORT
              value: {{ .Values.analyticsService.envVars.MONGO2_PORT | quote  }}

          ports:
            - name: analytics-ser
              containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-ser
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: analytics-ser
  selector:
    app: analytics-ser
  type: ClusterIP
