---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    velocity.tech.v1/id: service
    velocity.tech.v1/dependsOn: mongo2
  name: service
  labels:
    app: service
spec:
  selector:
    matchLabels:
      api: service
  replicas: 1
  template:
    metadata:
      labels:
        app: service
        api: service
    spec:
      containers:
        - name: service
          image: jdvincent/gin_redis_service:latest
          env:
            - name: MONGO2_HOST
              value: {{ .Values.mongo2_host | toJson  }}
            - name: MONGO2_PORT
              value: {{ .Values.mongo2_port | toJson  }}
          ports:
            - name: service
              containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: service
  selector:
    app: service
  type: ClusterIP
