mongo1_port: "{velocity.v1:mongo1.exposures(port=mongo1).port}"
mongo1_host: "{velocity.v1:mongo1.exposures(port=mongo1).host}"
mongo2_port: "{velocity.v1:mongo2.exposures(port=mongo2).port}"
mongo2_host: "{velocity.v1:mongo2.exposures(port=mongo2).host}"
redis_port: "{velocity.v1:redis.exposures(port=redis).port}"
redis_host: "{velocity.v1:redis.exposures(port=redis).host}"
service_port: "{velocity.v1:service.exposures(port=service).port}"
service_host: "{velocity.v1:service.exposures(port=service).host}"
web_api_host: "{velocity.v1:web-api.exposures(port=web-api).host}"
web_api_port: "{velocity.v1:web-api.exposures(port=web-api).port}"
ingress_host: "api-{velocity.v1.domainSuffix}"
ingress_class_name: null
protocol: "https"
host: "api-{velocity.v1.domainSuffix}"