on:
  push:
    branches:
      - dev
jobs:
  build_container_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./redis-gin-mongo/src/blog_service
          file: ./redis-gin-mongo/src/blog_service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/gin-blog:latest
  
  create_velocity_preview_env:
    runs-on: ubuntu-latest
    needs: build_container_image
    steps:
    
    - uses: techvelocity/env-name-action@v1
      id: env-name
      
    - uses: techvelocity/env-create-action@v1
      with:
        velocity-token: ${{ secrets.VELOCITY_TOKEN }}
        services: ${{ env.VELOCITY_SERVICE }}
        name: ${{ steps.env-name.outputs.name }}
        use-gh-deployments: 'false'
        use-gh-comments: 'false'
    env:
      VELOCITY_SERVICE: blog
    outputs:
      env_name: ${{ steps.env-name.outputs.name }}
  
#   destroy_velocity_preview_env:
#     runs-on: ubuntu-latest
#     needs: create_velocity_preview_env
#     - uses: techvelocity/env-destroy-action@v1
#       with:
#         velocity-token: ${{ secrets.VELOCITY_TOKEN }}
#         name: ${{ needs.create_velocity_preview_env.outputs.env_name }}
